version: "2"

formatters:
  enable:
    - gofmt

linters:
  disable:
    - tagliatelle
    - nlreturn
    - lll
    - godot
    - varnamelen
    - ireturn
    # TODO
    - dupl
    - wrapcheck
    - testpackage
    - godox
    - nestif
    - funlen
    - gocognit
    - gocyclo
